export default Object.freeze({
    HOME:"Home",
    ACCOUNT: "Account",
    ADDCATEGORY: "AddCategory",
    ADDITEM: "AddItem",
    BANKDETAILS: "BankDetails",
    BUSSINESSDETAILS: "BussinessDetails",
    CREATESHOP: "CreateShop",
    LANDINGPAGE: "LandingPage",
    LOADING: "Loading",
    LOGIN: "Login",
    MYCATEGORIES: "MyCategories",
    MYITEMS: "MyItems",
    MYORDERS: "MyOrders",
    MYSHOP: "MyShop",
    NAVIGATIONAPP:"NavigationApp",
    NEWSHOPNAVIGATOR: "NewShopNavigator",
    NOCATEGORIES: "NoCategories",
    NOITEMS: "NoItems",
    NOSHOP: "NoShop",
    NOTREGISTER: "NotRegistered",
    REGISTER: "Register",
    SERVERERROR: "ServerError",
    SHOPNAVIGATOR: "ShopNavigator",
  });