export default Object.freeze({
  ACCOUNT: "Account",
  APPNAVIGATOR: "AppNavigator",
  CARTITEMS: "CartItems",
  CATEGORIES: "Categories",
  HOME: "Home",
  LANDINGPAGE: "LandingPage",
  LOGIN: "Login",
  NOTREGISTER: "NotRegistered",
  OFFERS: "Offers",
  REGISTER: "Register",
  SHOPITEMS: "ShopItems",
  SHOPS: "shops",
  WHISLIST: "WhisList",
});